### ISSUE TITLE
GetComponentInParent не лучшая идея

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/vgusphere-clicker#3]
Если тебе постоянно нужно использовать какой-то объект на компоненте - делай его переменной с атрибутом [SerializeField]
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/Cubes.cs#L12

**Comment by bbno-c** [comment]
Как же тогда можно получить доступ к сеттеру в объекте класса Spawner из объекта класса Cube?

**Comment by Red-Cat-Fat** [comment]
Прокидывать его в момент спавна

**Comment by bbno-c** [comment]
> Прокидывать его в момент спавна

Подкинуть автоматически можно только через трансформ ведь?

```
public class Cubes : MonoBehaviour
{
    [SerializeField] private Spawner _spawnerScript;

    private void Start()
    {
        _spawnerScript = transform.GetComponentInParent<Spawner>();
    }
}
```

**Comment by Red-Cat-Fat** [comment]
Почитай книгу по C# какую - нибудь. Или хотя бы [Metanit](https://metanit.com/sharp/).
Прокидывать класс и компонент можно через функцию в качестве аргумента.

**Comment by bbno-c** [comment]
https://github.com/bbno-c/Lesson-2.-Clicker/commit/4254f078e43bc48d3176527b8f1bec5874f9aff0

**Comment by Red-Cat-Fat** [comment]
Не нужно пихать сразу все правки в один коммит и говорить "Ну где-то там, найдёшь". Хоть бы комментарий оставил что ты сделал
