### ISSUE TITLE
Лишние переменные

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/vgusphere-clicker#5]
Если ты что-то не использешь - удаляй
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/MouseCoordinates.cs#L10

**Comment by bbno-c** [comment]
Убрал весь скрипт, но не нашел комит где это отображено

**Comment by Red-Cat-Fat** [comment]
И я не могу найти)

**Comment by bbno-c** [comment]
Нашел.
https://github.com/bbno-c/Lesson-2.-Clicker/commit/1c53b1979d050aa0454d81d17de3c69b8919cf6c#diff-130b0e7bbad24bae2c4fa0de6e4d20dd

**Comment by Red-Cat-Fat** [comment]
Отписался в комите
