### ISSUE TITLE
Нельзя использовать FindGameObjects через рефлексию

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/vgusphere-clicker#8]
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/spawner.cs#L48

**Comment by Red-Cat-Fat** [comment]
Просто у тебя может запросто заспавниться левый объект с похожим именем

**Comment by bbno-c** [comment]
А можно через трансформ?
https://github.com/bbno-c/Lesson-2.-Clicker/commit/3567e5ad0f593cc5691b20474353dfc0c50c951b
https://github.com/bbno-c/Lesson-2.-Clicker/commit/cb649f5c06497739cfd0360b0ad66cbbf4fac298

**Comment by Red-Cat-Fat** [comment]
Достаточно только родительский компонент удалить - дочерние уничтожатся

**Comment by bbno-c** [comment]
А если родительский это спавнер?

**Comment by Red-Cat-Fat** [comment]
Тогда создай компонент, который будет уничтожать объекты и повесь его на нужные тебе компоненты

**Comment by bbno-c** [comment]
Можно использовать такой метод?
В конце игры спавнер отключается, и его дети(кубы) тоже. У кубов, при отключении срабатывает Destroy. https://github.com/bbno-c/Lesson-2.-Clicker/commit/4254f078e43bc48d3176527b8f1bec5874f9aff0

**Comment by Red-Cat-Fat** [comment]
Это не так удобно в перспективе. Вдруг дизайнеры захотят делать различные ограничения по времени для разных префабов? Всегда стоит смотреть в будущее, чтобы сделать использование кода более удобным
