### ISSUE TITLE
Нет проверки на null

### ISSUE THREAD

**Issue by Red-Cat-Fat** [bbno-c/vgusphere-clicker#9]
https://github.com/bbno-c/Lesson-2.-Clicker/blob/4ce2cb06981105da4595709edf05ac7614cbe280/Assets/Scripts/spawner.cs#L60

**Comment by bbno-c** [comment]
Перед тем как вызвать событие проверяется делегат End/NewGameEvent на NULL
https://github.com/bbno-c/Lesson-2.-Clicker/commit/43e56f9b8b3a6a6b2fa7f1433dbebb062b52e06e

**Comment by Red-Cat-Fat** [comment]
Но не проверяется GameProxy
![image](https://user-images.githubusercontent.com/28541280/77256633-88812480-6c80-11ea-97d8-cc722c01e568.png)
